---

- name: Install iptables-nft and wireguard
  ansible.builtin.package:
    name:
      - iptables-nft
      - wireguard-tools

- name: Alloww IP forwarding
  ansible.posix.sysctl:
    name: '{{ item }}'
    value: '1'
    sysctl_set: true
    sysctl_file: /etc/sysctl.d/wg.conf
  loop:
    - net.ipv4.ip_forward
    - net.ipv6.conf.all.forwarding

- name: Configure WireGuard
  ansible.builtin.template:
    src: wg0.conf
    dest: /etc/wireguard/wg0.conf
    owner: root
    group: root
    mode: '0600'
  notify: Restart WireGuard

- name: Enable WireGuard
  ansible.builtin.service:
    name: wg-quick@wg0
    state: started
    enabled: true
