---
dependency:
  name: galaxy
driver:
  name: delegated
  options:
    managed: false
    login_cmd_template: ssh {instance}
    ansible_connection_options:
      ansible_connection: ssh
platforms:
  - name: test.el9
lint: |
  set -e
  yamllint .
  ansible-lint
provisioner:
  name: ansible
verifier:
  name: ansible
