---

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Check if WireGuard interface is available
      ansible.builtin.command:  # noqa no-changed-when command-instead-of-module
        cmd: ip a show wg0
